# Orb 'circleci/python@0.2.1' resolved to 'circleci/python@0.2.1'
version: 2
jobs:
  build-and-test:
    docker:
    - image: circleci/python:latest
    steps:
    - checkout
    - restore_cache:
        keys:
        - pip-{{ checksum "requirements.txt"  }}
    - run:
        command: |
          if true; then
            pip install --user -r requirements.txt
          else
            pip install -r requirements.txt
          fi
        name: Install Dependencies
    - save_cache:
        key: pip-{{ checksum "requirements.txt"  }}
        paths:
        - /home/circleci/.local/lib/
    - run:
        name: run lint
        command: |
          . hello/bin/activate
          make lint
workflows:
  main:
    jobs:
    - build-and-test
  version: 2